import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] pt-10">
        {/* Weather Card */}
        <div className="relative flex flex-col items-center justify-center rounded-xl bg-black/30 p-10 text-white">
          <input
            type="text"
            placeholder="Enter city name here"
            className="absolute top-[-4rem] w-full rounded-md border border-white/50 bg-transparent py-2 text-center text-lg placeholder:text-white/30"
          />
          <div className="text-xl tracking-wider">Nakhon Ratchasima</div>
          <div>
            <div className="flex items-center">
              <Image
                alt="weather-icon"
                width={100}
                height={100}
                src={`https://openweathermap.org/img/wn/01d.png`}
              />
              <div>
                <div className="text-2xl font-bold">26 °C</div>
                <div className="flex gap-2 text-xs text-white/50">
                  <div>min/max </div>
                  <div>24/30 °C</div>
                </div>
              </div>
            </div>

            <div className="grid grid-flow-col grid-rows-1 gap-4">
              <div className="grid grid-cols-1 place-items-center rounded-lg border border-white/50 p-2 text-center">
                <div className=" font-bold">Clear</div>
                <div className="text-sm text-white/80">clear sky</div>
              </div>
              <div className="grid grid-cols-1 place-items-center rounded-lg border border-white/50 p-2 text-center">
                <div className="text-base font-bold">Humidity</div>
                <div className="text-sm">69%</div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
